### ISSUE TITLE
Eliminate OptionsPanelComponent.picColors

### ISSUE THREAD

**Issue by pawooten** [pawooten/ng-camera-game#4]
`OptionsPanelComponent` declares two members: `picColors` and `picColorStates`. Within `ngOnInit()`, both members are assigned to the same `PicColorState[]` retrieved from `OptionsService`. `picColors` was introduced as a workaround; attempting to index `picColorStates` instead of `picColor` in `<app-pic-color-canvas [(PicColor)]="picColors[i]"></app-pic-color-canvas>` results in "Error: src/app/components/options-panel/options-panel.component.html:11:57 - error TS2741: Property 'Enabled' is missing in type 'PicColor' but required in type 'PicColorState'."

I thought I should be able to provide a `PicColorState` to satisfy the `PicColor` input of `PicColorCanvas` since `PicColorState` extends `PicColor`.

**Comment by cgatian** [comment]
Looks like `PicColorCanvasComponent` is using `PicColorState`. Youre saying there's a type that hasn't been defined yet, `PicColor` that you want to provide as the input for this component?
```ts
export class PicColorCanvasComponent implements OnInit {

  @Input() PicColor! : PicColorState;
```

**Comment by cgatian** [comment]
Oh, you have a branch for this? Checkout my PR #5
